# action.yml
name: SeleniumCICD
description: Run docker with selenium, python, pytest and pytest allure
author: Nakajiss <smoke42rus81@gmail.com>

branding:
  color: blue
  icon: feather

inputs:
  test-plan-path:
    required: true
    description: python test plan to execute
  args:
    required: false
    description: Optional arguments.
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "${{ inputs.test-plan-path }}"
