# action.yml
name: SeleniumCICD
description: Run docker with selenium, python, pytest and pytest allure
author: Nakajiss <smoke42rus81@gmail.com>

branding:
  color: blue
  icon: feather

# inputs:
#   args:
#     required: false
#     description: Optional arguments. For more details https://jmeter.apache.org/usermanual/get-started.html#non_gui

runs:
  using: 'docker'
  image: 'Dockerfile'
#   args:
#   - "${{ inputs.args }}"
