on: [push]
jobs:
  selenium_job:
    runs-on: ubuntu-latest
    name: Selenium Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Selenium Tests
        uses: ./
        with:
          args: ""
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: allure_result/*.json
